"""Locating the transaction table inside an eSewa Statement export and
turning it into StatementRows.

rows_from_sheet_values is tested against plain Python lists shaped like
xlrd's sheet.row_values() output (see its docstring for why).
rows_from_workbook_bytes and EsewaStatementFileParser get one real
in-memory .xls, built with xlwt, to prove the base64 -> xlrd -> rows ->
NormalizedTxn path actually works end to end -- xlwt is a test-only
dependency (pyproject.toml's dev extra), never shipped.
"""

from __future__ import annotations

import base64
import io

import pytest
import xlwt

from expense_tracker.ingest.esewa_statement_file import (
    rows_from_sheet_values,
    rows_from_workbook_bytes,
    whole_file_raw_message_fields,
)
from expense_tracker.parsers.esewa_statement import SENDER, EsewaStatementFileParser
from expense_tracker.parsers.sms import SmsMessage

_HEADER = ["Reference Code", "Date Time", "Description", "Dr.", "Cr.", "Status", "Balance (NPR)", "Channel"]

# Shape of a real export: a report header, then the column header, then
# data rows, then a "Total" line and per-status counts.
_SHEET = [
    ["Statement Report", "", "", "", "", "", "", ""],
    ["", "", "", "", "", "", "", ""],
    ["From Date", "Mon Sep 07 00:00:00 NPT 2026", "To Date", "Mon Sep 14 23:59:59 NPT 2026", "", "", "", ""],
    ["Generated On", "2026-09-14 15:42:21", "Status", "ALL", "", "", "", ""],
    ["Channel", "ALL", "Dr/Cr", "ALL", "", "", "", ""],
    ["Generated by", "9800000000", "", "", "", "", "", ""],
    ["", "", "", "", "", "", "", ""],
    ["", "", "", "", "", "", "", ""],
    _HEADER,
    ["1R1G2EC", "2026-09-14 13:40:57.0", "Fund Transferred to Test Person", "370.0", "0.0", "COMPLETE", "4544.77", "App"],
    ["1QYGXXX", "2026-09-13 10:00:00.0", "Failed transfer", "50.0", "0.0", "PENDING", "5000.00", "App"],
    ["1QYGCB7", "2026-09-13 13:09:41.0", "Paid for Some Merchant", "999.0", "0.0", "COMPLETE", "4729.77", "Linked Esewa Payment"],
    ["", "", "Total", "1369.0", "0.0", "", "", ""],
    ["", "", "", "", "", "", "", ""],
    ["Total", "3", "", "", "", "", "", ""],
]


def _xls_bytes(sheet_rows: list[list]) -> bytes:
    book = xlwt.Workbook()
    sheet = book.add_sheet("eSewa Report")
    for r, row in enumerate(sheet_rows):
        for c, value in enumerate(row):
            sheet.write(r, c, value)
    buf = io.BytesIO()
    book.save(buf)
    return buf.getvalue()


def test_finds_the_header_regardless_of_the_report_preamble_length():
    rows = rows_from_sheet_values(_SHEET)
    assert [r.reference for r in rows] == ["1R1G2EC", "1QYGCB7"]


def test_non_complete_rows_are_skipped():
    rows = rows_from_sheet_values(_SHEET)
    assert "1QYGXXX" not in [r.reference for r in rows]


def test_stops_at_the_total_row_rather_than_reading_the_footer():
    rows = rows_from_sheet_values(_SHEET)
    assert all(r.reference != "Total" for r in rows)
    assert len(rows) == 2


def test_row_fields_are_carried_through():
    (row, _) = rows_from_sheet_values(_SHEET)
    assert row.reference == "1R1G2EC"
    assert row.datetime_str == "2026-09-14 13:40:57.0"
    assert row.description == "Fund Transferred to Test Person"
    assert row.dr == "370.0"
    assert row.cr == "0.0"
    assert row.balance == "4544.77"
    assert row.channel == "App"


def test_header_missing_is_a_clear_error_not_an_index_crash():
    with pytest.raises(ValueError, match="header row not found"):
        rows_from_sheet_values([["nothing", "to", "see"]])


def test_rows_from_workbook_bytes_reads_a_real_xls():
    rows = rows_from_workbook_bytes(_xls_bytes(_SHEET))
    assert [r.reference for r in rows] == ["1R1G2EC", "1QYGCB7"]


def test_whole_file_raw_message_fields_round_trips_through_the_real_parser():
    file_bytes = _xls_bytes(_SHEET)
    fields = whole_file_raw_message_fields(file_bytes)
    assert fields["sender"] == SENDER
    assert base64.b64decode(fields["body"]) == file_bytes

    message = SmsMessage(
        id="raw-1", sender=fields["sender"], body=fields["body"],
        received_at=fields["received_at"], content_hash=fields["content_hash"],
    )
    parser = EsewaStatementFileParser()
    assert parser.matches(message)
    txns = parser.parse(message)

    assert [t.reference for t in txns] == ["1R1G2EC", "1QYGCB7"]
    assert txns[0].direction == "DEBIT"
    assert txns[0].balance_after_paisa == 454_477
    assert txns[0].counterparty == "Test Person"
