#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

EXPENSE_TRACKER_HOME="$HOME/.expense-tracker"
mkdir -p "$EXPENSE_TRACKER_HOME"
ENV_FILE="$EXPENSE_TRACKER_HOME/.env"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

banner "Expense tracker: Phase 2 infrastructure setup"

# ── Stage 1: create the Supabase project ───────────────────────────────────
stage "Create your Supabase project"
say "This is the shared ledger -- section 1/4 of the plan. It holds only"
say "structured rows, never email bodies or the IMAP password."
open_url "https://supabase.com/dashboard/projects"
step "Sign in, then 'New project'. Pick any org, a name (e.g. expense-tracker),"
step "a strong database password (save it somewhere -- Supabase won't show it"
step "again), and the region closest to you."
step "Wait for provisioning to finish (a minute or two), then open the project."
step "Project Settings (gear icon) → General → copy the 'Reference ID'."
ask PROJECT_REF "Paste the project reference ID:"
note "Used below to build direct links into the rest of the dashboard."

# ── Stage 2: direct Postgres connection string ─────────────────────────────
stage "Get the direct Postgres connection string"
say "The worker does bulk upserts with psycopg (plan section 5) -- it wants"
say "the *direct* connection, not the pgbouncer/transaction pooler one."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/settings/database"
step "Under 'Connection string', select the 'URI' tab and make sure the mode"
step "is 'Direct connection' (not 'Transaction pooler' / 'Session pooler')."
step "Copy it, then paste below and replace [YOUR-PASSWORD] with the DB"
step "password you set in stage 1."
ask_secret EXPENSE_TRACKER_DB_URL "Paste the direct connection string:"
write_env EXPENSE_TRACKER_DB_URL "$EXPENSE_TRACKER_DB_URL"

# ── Stage 3: apply the schema migration ─────────────────────────────────────
stage "Apply the schema migration"
say "supabase/migrations/20260901000000_initial_schema.sql -- tables, RLS,"
say "the security_invoker view. Two ways to run it; pick whichever's less friction."
say ""
if command -v supabase >/dev/null 2>&1; then
  note "Supabase CLI found."
  if confirm "Link this repo and push the migration now (supabase link + db push)?"; then
    (cd "$REPO_ROOT" && supabase link --project-ref "$PROJECT_REF" && supabase db push) \
      && note "migration pushed" \
      || warn "CLI push failed -- fall back to the SQL editor below"
  fi
else
  note "Supabase CLI not found (brew install supabase/tap/supabase to get it)."
fi
say "Zero-install fallback: paste the SQL directly."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/sql/new"
step "Open ${REPO_ROOT}/supabase/migrations/20260901000000_initial_schema.sql"
step "in an editor, copy the whole file, paste it into the SQL editor, and hit Run."
pause "Press Enter once the migration has run without errors."

# ── Stage 4: create your auth user ──────────────────────────────────────────
stage "Create your Supabase Auth user"
say "Every table is keyed by user_id + RLS (plan section 11.2), even for a"
say "single user -- this is the row everything else hangs off."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/users"
step "Click 'Add user' → 'Create new user'. Any email + password works --"
step "this account is only used by you, from the worker and later the app."
step "Click into the new user and copy their UID (a UUID)."
ask EXPENSE_TRACKER_USER_ID "Paste the user UUID:"
write_env EXPENSE_TRACKER_USER_ID "$EXPENSE_TRACKER_USER_ID"

# ── Stage 5: seed starter categories ────────────────────────────────────────
stage "Seed starter categories"
say "supabase/seed.sql has the starting category list from plan section 10"
say "(Food, Groceries, Transport, ... Transfer, Salary marked is_spend=false)."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/sql/new"
step "Open ${REPO_ROOT}/supabase/seed.sql, copy its contents into the SQL editor,"
step "then replace every :'user_id' with '${EXPENSE_TRACKER_USER_ID}' (with the"
step "quotes) before running it -- the file uses a psql variable that the web"
step "SQL editor can't substitute for you."
pause "Press Enter once the categories are inserted."

# ── Stage 6: Gmail app password ─────────────────────────────────────────────
stage "Gmail app password for IMAP"
say "This is separate from any Gmail OAuth access already granted elsewhere --"
say "it's a standalone app password the worker's IMAP client (imap-tools) uses"
say "to read the inbox directly. Needs 2-Step Verification already on."
open_url "https://myaccount.google.com/apppasswords"
step "Sign in as the Google account whose inbox receives your bank mail,"
step "create an app password (name it 'expense-tracker'), and copy the"
step "16-character password."
step "Enter it with the spaces removed."
ask_secret EXPENSE_TRACKER_IMAP_PASSWORD "Paste the app password (spaces will be stripped):"
EXPENSE_TRACKER_IMAP_PASSWORD="${EXPENSE_TRACKER_IMAP_PASSWORD// /}"
write_env EXPENSE_TRACKER_IMAP_PASSWORD "$EXPENSE_TRACKER_IMAP_PASSWORD"

# ── Stage 7: local config.toml ──────────────────────────────────────────────
stage "Write ~/.expense-tracker/config.toml"
say "The non-secret half of the worker's config (plan section 3); .env above"
say "holds the secrets, this holds everything else."
DEFAULT_MACHINE=$(hostname -s 2>/dev/null || hostname)
ask WORKER_MACHINE "Name for this machine [${DEFAULT_MACHINE}]:"
WORKER_MACHINE="${WORKER_MACHINE:-$DEFAULT_MACHINE}"
ask IMAP_USERNAME "Email address the worker reads (IMAP username):"
ask ACCOUNT_START "Earliest date to backfill from, YYYY-MM-DD [2025-01-01]:"
ACCOUNT_START="${ACCOUNT_START:-2025-01-01}"
CONFIG_PATH="$EXPENSE_TRACKER_HOME/config.toml"
cat > "$CONFIG_PATH" <<TOML
[worker]
machine = "${WORKER_MACHINE}"
archive_dir = "~/.expense-tracker/raw"
account_start = "${ACCOUNT_START}"

[imap]
host = "imap.gmail.com"
username = "${IMAP_USERNAME}"

[senders]
esewa = "esewa.com.np"
nabil = "nabilbank.com"
TOML
printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$CONFIG_PATH"

# ── Stage 8: smoke test ─────────────────────────────────────────────────────
stage "Smoke test"
say "Confirms config.toml + .env are wired up before trusting a real sync."
VENV_CLI="$REPO_ROOT/worker/.venv/bin/expense-tracker"
if [[ -x "$VENV_CLI" ]]; then
  step "Running: expense-tracker status"
  if "$VENV_CLI" status; then
    note "status OK. When you're ready:"
    note "  $VENV_CLI sync"
    note "runs the first real sync against your Supabase project."
  else
    warn "status failed -- check config.toml / .env above for typos and re-run this wizard."
  fi
else
  warn "worker/.venv not found -- from worker/, run: python3 -m venv .venv && .venv/bin/pip install -e '.[dev]'"
  note "then: $VENV_CLI status"
fi

# ── Stage 9: schedule the twice-daily sync ──────────────────────────────────
stage "Schedule the twice-daily sync"
say "Section 6.4 -- a systemd --user timer on Linux, a launchd agent on macOS."
say "Runs at 10:30 and 21:30; the evening one refreshes ledger gaps just"
say "before the app's 22:00 reminder. Both re-run a missed job on wake."
SCHED_DIR="$REPO_ROOT/worker/src/expense_tracker/scheduling"
LOG_DIR="$EXPENSE_TRACKER_HOME/logs"
mkdir -p "$LOG_DIR"

if [[ "$(uname -s)" == "Linux" ]] && command -v systemctl >/dev/null 2>&1; then
  if confirm "Install and enable the systemd --user timer now?"; then
    UNIT_DIR="$HOME/.config/systemd/user"
    mkdir -p "$UNIT_DIR"
    sed "s|__WORKING_DIRECTORY__|$REPO_ROOT/worker|g; s|__EXEC_START__|$VENV_CLI sync|g" \
      "$SCHED_DIR/expense-sync.service" > "$UNIT_DIR/expense-sync.service"
    cp "$SCHED_DIR/expense-sync.timer" "$UNIT_DIR/expense-sync.timer"
    systemctl --user daemon-reload
    systemctl --user enable --now expense-sync.timer
    note "installed to $UNIT_DIR, enabled. Check: systemctl --user status expense-sync.timer"
  else
    SKIPPED+=("systemd timer -- install by hand from $SCHED_DIR")
  fi
elif [[ "$(uname -s)" == "Darwin" ]]; then
  if confirm "Install and load the launchd agent now?"; then
    AGENT_DIR="$HOME/Library/LaunchAgents"
    mkdir -p "$AGENT_DIR"
    PLIST_NAME="com.expensetracker.sync.plist"
    sed "s|__EXEC_PATH__|$VENV_CLI|g; s|__WORKING_DIRECTORY__|$REPO_ROOT/worker|g; s|__LOG_DIR__|$LOG_DIR|g" \
      "$SCHED_DIR/$PLIST_NAME" > "$AGENT_DIR/$PLIST_NAME"
    launchctl unload "$AGENT_DIR/$PLIST_NAME" >/dev/null 2>&1 || true
    launchctl load -w "$AGENT_DIR/$PLIST_NAME"
    note "installed to $AGENT_DIR, loaded. Logs: $LOG_DIR/expense-sync.log"
  else
    SKIPPED+=("launchd agent -- install by hand from $SCHED_DIR")
  fi
else
  warn "unrecognized OS -- install the unit in $SCHED_DIR by hand."
  SKIPPED+=("scheduling -- install by hand from $SCHED_DIR")
fi
note "raw/ retention (section 11.3) isn't scheduled automatically -- run"
note "  $VENV_CLI retention"
note "occasionally by hand, or add it to your own cron/timer."

finish
